name: Build Check

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs pull

      - name: Set up JDK Zulu 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Run Screenshot Tests
        run: ./gradlew verifyRoborazziDebug
        continue-on-error: true

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: app/build/reports

      - name: Upload Roborazzi outputs
        uses: actions/upload-artifact@v4
        with:
          name: roborazzi-outputs
          path: app/build/outputs