name: Build Check

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK Zulu 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Prepare
        run: ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Run Screenshot Tests
        run: ./gradlew verifyRoborazziDebug